add-bookings
srg391/java-shareit pull request #2
Opened 2022-11-17 03:00 UTC by srg391

add-bookings

2022-11-21 17:58 UTC, Frilock requested changes
Добрый вечер, работу посмотрел, оставил ряд комментариев к ней. Жду новую версию

2022-11-21 17:58 UTC, Frilock commented on pom.xml
> +		<dependency>
Общий комментарий, у тебя 48 коммитов которые не имеют никакого описания. Это не правильно. Сделай squash этих коммитов в один. Кроме того, когда ты делаешь пул реквест или коммит, нужно давать какое то адекватное описание проделанной работы. Это некий стандарт

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingDto bookingDto = bookingService.getBooking(userId, bookingId);
Съехало форматирование

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("SELECT b FROM Booking b WHERE b.booker.id = ?1 ORDER BY b.start DESC")
Смотрите, вы используете spring-data тут sql запрос генерируется по названию метода, и тут не нужно писать sql над каждым запросом, только над теми, где вы не можете уместить запрос в название или где название получается очень большим и не читаемым. В вашем же случае вы над всеми методами пишите sql

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingState.java
> +    REJECTED, UNSUPPORTED_STATUS;
UNSUPPORTED_STATUS надо на новую строчку перенести

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/EndAfterStartValidator.java
> +
Лишняя пустая строчка

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/EndAfterStartValidator.java
> +        return (startAndEndBookingDto.getStart().isAfter(currentDate) || startAndEndBookingDto.getStart().isEqual(currentDate))
А тут не нужно проверять что startAndEndBookingDto.getStart() и startAndEndBookingDto.getEnd() null не вернут?

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +        Long id;
Предлагаю для единообразия добавить приватный модификатор сюда и в класс ниже тоже

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item: items) {
перед : пробел

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>              if (itemDto.getName() != null) {
Можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/comment/CommentMapper.java
> +@RequiredArgsConstructor
Лишняя аннотация, не вижу для чего она тут

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemWithBookingDto.java
> +        Long id;
Предлагаю модификаторы указать

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Column(name = "description", nullable = false)
По хорошему тут нужно еще указывать размерность полей, которую вы в скриптах указываете. Чтобы каждый раз в скрипты не лазить для уточнения

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +//        if (userDto.getEmail() == null) {
Надо убрать закоментированный код

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (userDto.getEmail() != null) {
Предлагаю валидацию в отдельный приватный метод вынести

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            } else throw new InvalidEmailException("Email не соотвествует!");
блок else все равно лучше обособлять скобками { и }

2022-11-21 17:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
>      @NotBlank(groups = {Create.class})
А разве остается нужна NotBlank? Email не включает разве проверки необходимые?

2022-11-21 17:58 UTC, Frilock commented on src/main/resources/schema.sql
> +    start_date TIMESTAMP without time zone,
Давайте форматирование столбиков выровняем

2022-11-30 19:59 UTC, srg391 commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
>      @NotBlank(groups = {Create.class})
@Email проверяет только соответствие адреса правилам написания адреса.

2022-11-30 20:40 UTC, srg391 commented on pom.xml
> +		<dependency>
Не получилось сделать git squah не смотря на все попытки. Пишет что для коммитов которые я хочу объединить существует два родителя и не соединяет. Единственный результат это Merge remote-tracking branch 'origin/add-bookings' into add-bookings он получился, а вот соединить не нужные коммиты в один или удалить не получается.

2022-12-01 08:17 UTC, Frilock requested changes
Добрый день, все в целом хорошо, однако, написал еще пару мелких комментариев. Если с чем то не согласны, можете на комментарий мне тут ответить.

2022-12-01 08:17 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("SELECT b FROM Booking b WHERE b.booker.id = ?1 AND b.start<?2 AND b.end > ?3 ORDER BY b.start DESC")
Вроде писал Вам о том, что нет смысла везде свой SQL писать в Query, если запрос нормально в название метода укладывается

2022-12-01 08:17 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/StartAndEndBookingDto.java
> +@EqualsAndHashCode(of = "id")
Но тут нет поля id... либо вы его забыли указать либо это itemId

2022-12-01 08:17 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/BookingMapper.java
> +@Service
Лучше Component, особой разницы конечно нет, но все таки вряд ли маппер сервисом можно назвать =)

2022-12-01 08:17 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/BookingMapper.java
> +    public BookingDto createDtoBooking(Booking booking) {
Я вот думаю, мне кажется что лучше бы еще входной параметр проверять на != null, или поставить у аргумента аннотацию nonNull, чтобы было более понятно

2022-12-01 08:17 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    @Transactional
Можно readOnly

2022-12-02 20:30 UTC, srg391 commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("SELECT b FROM Booking b WHERE b.booker.id = ?1 AND b.start<?2 AND b.end > ?3 ORDER BY b.start DESC")
Поменял два метода без Query, остальные получаются с очень длинными, плохочитаемыми названиями. Если посмотреть на код с такими названиями я могу запутаться что написано.

2022-12-03 09:07 UTC, Frilock approved these changes
ПРинято

2022-12-03 17:16 UTC, merged